name: deploy-static-website

on:
  push:
    branches:
      - develop  # Set a branch to deploy
    tags:
      - '*.*.*' # from .env of dev

jobs:
  to-production:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # ref: main
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # hugo-version: 'latest'
          hugo-version: '0.82.0'
          extended: true

      - name: Clean public directory
        run: rm -rf public

      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/hugo_cache
      #     key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-hugomod-

      - name: Build
        # run: hugo -D
        run: |
          cd Beverly/
          hugo --gc --minify --cleanDestinationDir

      # - name: Prepare tag
      #   id: prepare_tag
      #   if: startsWith(github.ref, 'refs/tags/') != true
      #   # if: "!startsWith(github.ref, 'refs/tags/')"
      #   run: |
      #     TAG_NAME=$(eval "cat ./.env | grep "STAGING_VERSION=*.*.*" | tr -d -c '[0-9 .]'")
      #     echo "::set-output name=tag_name::${TAG_NAME}"

      - name: Deploy
        # if: success() && github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: BeverlyBai
          user_email: tina49294929@gmail.com
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Beverly/public
          publish_branch: main
          # external_repository: robertchu1205/robertchu1205.github.io
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          commit_message: 'develop msg: ${{ github.event.head_commit.message }}'
          # commit_message: 'From Staging: ${GITHUB_REF##refs/tags/}'
          # tag_name: ${GITHUB_REF##refs/tags/}
          # tag_message: 'Staging: ${GITHUB_REF##refs/tags/}'